### ISSUE TITLE
zim: unsupported cluster compression

### ISSUE THREAD

**Issue by hollorol** [JojiiOfficial/ZimWiki#1]
# What I did
I have installed ZimWiki with go, downloaded a zim file, put into the library folder. 
# Expected behaviour
I have expected to see the wiki I downloaded, and the contents of it.
# Experienced behaviour
In the main page ZimWiki said "nothing is here", I can search for topics, but when I click any of them, it just shows nothing.
In the terminal I got the following error message:
![image](https://user-images.githubusercontent.com/15141218/106011236-8ebf0900-60ba-11eb-92db-524e59557e49.png)
# My system
OS: Debian 10
go version: 1.15.7

**Comment by gaetanlhf** [comment]
The library used to manage the zim archives (https://github.com/JojiiOfficial/go-zim) was not up to date, and thus did not yet support the new compressed zim archives in zstd format.
Pull request https://github.com/JojiiOfficial/go-zim/pull/1 and https://github.com/JojiiOfficial/ZimWiki/pull/2 fix this problem. :)
